deployTargetMap:
  dev01: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig-dev
  prod01: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig-prod
environmentMap:
  dev:
    deployTargetKey: dev01
  prod:
    deployTargetKey: prod01
git:
  buildVersionsUrl: git@github.com/jcantosz/build-versions.git
  credential: git
  email: jenkins@boxboat.com
  remotePathRegex: github\.com/(.*)\.git$
  remoteUrlReplace: git@github.com/{{ path }}.git
  branchUrlReplace: https://github.com/jcantosz/{{ path }}/tree/{{ branch }}
  commitUrlReplace: https://github.com/jcantosz/{{ path }}/commit/{{ hash }}
notifyTargetMap:
  default: !!com.boxboat.jenkins.library.notify.SlackWebHookNotifyTarget
    credential: slack-webhook-url
registryMap:
  default:
    scheme: https
    host: dtr.boxboat.com
    credential: registry
    imageUrlReplace: https://dtr.boxboat.com/repositories/{{ path }}/{{ tag }}/linux/amd64/layers
vaultMap:
  default:
    kvVersion: 1
    roleIdCredential: vault-role-id
    secretIdCredential: vault-secret-id
    tokenCredential: vault-token
    url: http://localhost:8200
repo:
  common:
    defaultBranch: sample 
    notifySuccessKeys:
      - default
    notifyFailureKeys:
      - default
    vaultKey: default
    eventRegistryKeys:
      - event: commit/sample
        registryKey: default
      - eventRegex: tag/(.*)
        registryKey: default
  promote:
    promotionMap:
      stage:
        event: commit/sample
        promoteToEvent: tag/rc
      prod:
        event: tag/rc
        promoteToEvent: tag/release
  deploy:
    deploymentMap:
      dev:
        environmentKey: dev
        event: commit/sample
        trigger: true
      stage:
        environmentKey: dev
        event: tag/rc
        trigger: true
      prod:
        environmentKey: prod
        event: tag/release
        trigger: false
